import os
import datetime

# For testing purposes.
iso_test = ["isotopomer C1 1 1 13C", "isotopomer C2 2 2 13C", "isotopomer O3 3 3 17O", "isotopomer C4 4 4 13C", "isotopomer C1 2 2 12C", "isotopomer O1 3 3 16O", "isotopomer C5 5 5 13C"]


def generate_conf(temperature: float, imag_threshold: float, isotopomers: list[str], filename: str = "autogenerated", scaling: float = 1.0, mass_override_isotopologue: str = "default", reference_isotopomer: str = "none"):
    SESSION_FOLDER = os.path.join('sessions', 'session_' + datetime.datetime.now().strftime("%Y_%m_%d_%H_%M_%S"))
    os.makedirs(SESSION_FOLDER, exist_ok=True)
    f = open(os.path.join(SESSION_FOLDER, filename + ".config"), "w")
    
    f.write("### THIS FILE HAS BEEN AUTOMATICALLY GENERATED ###\n\n\n")

    # scaling
    f.write("# scaling factor for frequencies\n")
    f.write(f"scaling {scaling}\n\n")
    
    # imaginary threshold
    f.write("# imaginaries less than this value in i*cm-1 will be ignored for the transition mode\n")
    f.write(f"imag_threshold {imag_threshold}\n\n")

    # temperature
    f.write("# temperature in K\n")
    f.write(f"temperature {temperature}\n\n")

    # light isotopomer mass replacement
    f.write("# specifies the masses used for the light isotopomer\n")
    f.write(f"mass_override_isotopologue {mass_override_isotopologue}\n\n")

    # reference isotopomer
    f.write("#all KIEs will be divided by the KIE at this position\n")
    f.write(f"reference_isotopomer {reference_isotopomer}\n\n")

    # isotopomer list
    f.write("# define the isotopomers\n")
    for isotopomer in isotopomers:
        f.write(f"{isotopomer}\n")
    f.write("\n")
    f.close()