import os
import datetime

# For testing purposes.
iso_test = ["isotopomer C1 1 1 13C", "isotopomer C2 2 2 13C", "isotopomer O3 3 3 17O", "isotopomer C4 4 4 13C", "isotopomer C1 2 2 12C", "isotopomer O1 3 3 16O"]


def generate_conf(temperature: float, imag_threshold: float, isotopomers: list[str], filename: str = "autogenerated", scaling: float = 1.0, mass_override_isotopologue: str = "default", reference_isotopomer: str = "none"):
    SESSION_FOLDER = os.path.join('sessions', 'session_' + datetime.datetime.now().strftime("%Y_%m_%d_%H_%M_%S"))
    os.makedirs(SESSION_FOLDER, exist_ok=True)
    f = open(os.path.join(SESSION_FOLDER, filename + ".config"), "w")
    f.write("testing")
    f.close()

generate_conf(100, 50, iso_test)
